import assert from 'node:assert/strict';
import { describe, test } from 'node:test';
import { AdminPhaseServiceError, transitionGamePhaseForAdmin } from '../lib/functions/src/admin/adminPhaseService.js';

const uid='trusted-admin'; const requestId='123e4567-e89b-42d3-a456-426614174000'; const now=1_800_000_000_000;
const catalog={ id:'final_01', area:'最終', region:'ALL', title:'Final', description:'Final mission', points:100, type:'PHOTO' };
function fixture({phase='PRE_GAME',admin=true,mission=catalog,configExtra={},missingConfig=false}={}) {
 const state={admin, config:missingConfig?null:{gameStatus:phase,day:1,startTime:77,isGameOver:false,isFinalMissionActive:false,finalMissionEndTime:0,activeFinalMissionId:null,logs:[],otherField:'keep',...configExtra}, mission, receipts:new Map(),writes:[],reads:[],failWrite:false};
 const store={runTransaction:async work=>{const pending=[];const tx={readAdmin:async id=>{state.reads.push('admin');return id===uid&&state.admin},readReceipt:async()=>{state.reads.push('receipt');return null},readConfig:async()=>{state.reads.push('config');return state.config&&structuredClone(state.config)},readMission:async id=>{state.reads.push(`mission:${id}`);return state.mission&&id===state.mission.id?structuredClone(state.mission):null},writeTransition:(actor,key,cfg,receipt)=>{state.writes.push('config');state.writes.push('receipt');pending.push(()=>{if(state.failWrite)throw Error('db');state.config={...state.config,...structuredClone(cfg)};state.receipts.set(key,structuredClone(receipt));});}};const result=await work(tx);pending.forEach(fn=>fn());return result;}};
 const runtime={now:()=>now,random:()=>0,createId:()=> 'server-log-id'};return {state,store,runtime};
}
const req=(action,extra={})=>({action,requestId,...extra});
describe('trusted admin phase service',()=>{
 test('writes transition and audit atomically with trusted identity fields and preserved config',async()=>{const f=fixture();const result=await transitionGamePhaseForAdmin(uid,req('START_DAY1'),f.store,f.runtime);assert.equal(result.newPhase,'DAY1_ACTIVE');assert.equal(f.state.config.startTime,now);assert.equal(f.state.config.otherField,'keep');assert.equal(f.state.config.logs[0].id,'server-log-id');assert.equal(f.state.config.logs[0].actorUid,uid);assert.equal(f.state.config.logs[0].action,'START_DAY1');assert.equal(f.state.config.logs[0].oldPhase,'PRE_GAME');assert.equal(f.state.receipts.size,1);assert.deepEqual(f.state.writes,['config','receipt']);});
 test('validates admin, request shape, config phase and transition before writes',async()=>{for(const [opts,body,reason] of [[{admin:false},req('START_DAY1'),'PERMISSION_DENIED'],[{},req('START_DAY1',{actor:'spoof'}),'INVALID_ARGUMENT'],[{},req('NOPE'),'INVALID_ARGUMENT'],[{phase:'corrupt'},req('PAUSE'),'INVALID_CONFIG'],[{phase:'GAME_OVER'},req('END_GAME'),'TRANSITION_NOT_ALLOWED']]){const f=fixture(opts);await assert.rejects(transitionGamePhaseForAdmin(uid,body,f.store,f.runtime),e=>e instanceof AdminPhaseServiceError&&e.reason===reason);assert.equal(f.state.writes.length,0);}});
 test('rejects invalid request IDs and missing Config without writes',async()=>{const f=fixture();await assert.rejects(transitionGamePhaseForAdmin(uid,{action:'START_DAY1',requestId:'bad'},f.store,f.runtime),e=>e.reason==='INVALID_ARGUMENT');const missing=fixture({missingConfig:true});await assert.rejects(transitionGamePhaseForAdmin(uid,req('START_DAY1'),missing.store,missing.runtime),e=>e.reason==='CONFIG_NOT_FOUND');assert.equal(f.state.writes.length,0);assert.equal(missing.state.writes.length,0);});
 test('selects and validates server catalog entry before any writes',async()=>{const f=fixture({phase:'DAY2_ACTIVE'});const result=await transitionGamePhaseForAdmin(uid,req('START_FINAL'),f.store,f.runtime);assert.equal(result.selectedFinalMissionId,'final_01');assert.equal(f.state.config.finalMissionEndTime,now+7_200_000);assert.deepEqual(f.state.reads,['admin','receipt','config','mission:final_01']);const missing=fixture({phase:'DAY2_ACTIVE',mission:null});await assert.rejects(transitionGamePhaseForAdmin(uid,req('START_FINAL'),missing.store,missing.runtime),e=>e.reason==='FINAL_MISSION_NOT_FOUND');assert.equal(missing.state.writes.length,0);});
 test('rejects a malformed catalog document and fixes clock, random, and audit ID once per invocation',async()=>{const f=fixture({phase:'DAY2_ACTIVE',mission:{...catalog,points:'100'}});await assert.rejects(transitionGamePhaseForAdmin(uid,req('START_FINAL'),f.store,f.runtime),e=>e.reason==='FINAL_MISSION_NOT_FOUND');assert.equal(f.state.writes.length,0);const valid=fixture({phase:'DAY2_ACTIVE'});let clocks=0,randoms=0,ids=0;const runtime={now:()=>{clocks++;return now;},random:()=>{randoms++;return 0;},createId:()=>{ids++;return'server-log-id';}};await transitionGamePhaseForAdmin(uid,req('START_FINAL'),valid.store,runtime);assert.deepEqual([clocks,randoms,ids],[1,1,1]);assert.equal(valid.state.config.logs[0].timestamp,now);});
 test('bounds logs and preserves idempotent receipt response without repeat writes',async()=>{const f=fixture({configExtra:{logs:Array.from({length:205},(_,i)=>i)}});await transitionGamePhaseForAdmin(uid,req('START_DAY1'),f.store,f.runtime);assert.equal(f.state.config.logs.length,200);const receipt=f.state.receipts.get(requestId);let reads=0;const replayStore={runTransaction:work=>work({...f.store,readAdmin:async()=>true,readReceipt:async()=>{reads++;return receipt},readConfig:async()=>{throw Error('must not read')},writeTransition:()=>{throw Error('must not write')}})};const replay=await transitionGamePhaseForAdmin(uid,req('START_DAY1'),replayStore,f.runtime);assert.equal(replay.duplicate,true);assert.equal(reads,1);});
 test('maps transaction failures and rejects without persisted partial state',async()=>{const f=fixture();f.state.failWrite=true;await assert.rejects(transitionGamePhaseForAdmin(uid,req('START_DAY1'),f.store,f.runtime),e=>e.reason==='PERSISTENCE_ERROR');assert.equal(f.state.config.gameStatus,'PRE_GAME');});
});
